version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  clearml-apiserver:
    image: allegroai/clearml:latest
    container_name: clearml-apiserver
    environment:
      - CLEARML_SERVER_TYPE=apiserver
    ports:
      - "8008:8008"  # API Server

  clearml-webserver:
    image: allegroai/clearml:latest
    container_name: clearml-webserver
    environment:
      - CLEARML_SERVER_TYPE=webserver
    ports:
      - "8080:8080"  # Web Server

  clearml-fileserver:
    image: allegroai/clearml:latest
    container_name: clearml-fileserver
    environment:
      - CLEARML_SERVER_TYPE=fileserver
    ports:
      - "8081:8081"  # Files Server

volumes:
  mongo_data:
  qdrant_storage:
  clearml_data: